# Generated by Django 4.2.9 on 2024-01-08 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Employee",
        ),
    ]
